name: "Import SARIF results from cov"

# Run workflow each time code is pushed to your repository and on a schedule.
# The scheduled workflow runs every Wednesday at 15:45 UTC.
on: 
  workflow_dispatch
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: checkout
        run: ls -al
      # Uploads results.sarif to GitHub repository using the upload-sarif action
      - uses: github/codeql-action/upload-sarif@v2
      # - name: import Sarif
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results2.sarif
          #sarif_file: webgoat-bd.sarif
